# Generated by Django 3.0.7 on 2020-12-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('tm', models.CharField(choices=[('Adana Toplum Merkezi', 'Adana Toplum Merkezi'), ('Ankara Toplum Merkezi', 'Ankara Toplum Merkezi'), ('Mersin Toplum Merkezi', 'Mersin Toplum Merkezi'), ('Merkez Ofis', 'Merkez Ofis')], default='Merkez Ofis', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255)),
                ('project_start', models.DateField()),
                ('project_finish', models.DateField()),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=25)),
                ('project_donor', models.CharField(choices=[('ALMAN KIZILHAÇI', 'ALMAN KIZILHAÇI'), ('NORVEÇ KIZILHAÇI', 'NORVEÇ KIZILHAÇI'), ('KATAR KIZILHAÇI', 'KATAR KIZILHAÇI')], default='ALMAN KIZILHAÇI', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='autority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Staff', 'Staff'), ('ProjectManager', 'ProjectManager'), ('Manager', 'Manager')], max_length=100)),
                ('tm', models.CharField(choices=[('Adana Toplum Merkezi', 'Adana Toplum Merkezi'), ('Ankara Toplum Merkezi', 'Ankara Toplum Merkezi'), ('Mersin Toplum Merkezi', 'Mersin Toplum Merkezi'), ('Merkez Ofis', 'Merkez Ofis')], max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
        ),
    
    ]
