# Generated by Django 3.0.7 on 2020-12-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='indic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indikator_name', models.CharField(max_length=200)),
                ('indikator_detail', models.CharField(max_length=1000)),
                ('indikator_hedef', models.IntegerField()),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
            options={
                'unique_together': {('proje', 'indikator_name')},
            },
        ),
    ]
